# Generated by Django 3.0.7 on 2020-06-23 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('F', 'First Player Turn'), ('S', 'Second Player Turn'), ('W', 'First player wins'), ('L', 'Second player wins')], default='F', max_length=1)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_first_player', to=settings.AUTH_USER_MODEL)),
                ('second_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_second_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cows', models.IntegerField()),
                ('bulls', models.IntegerField()),
                ('count', models.IntegerField()),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowsbulls.Choice')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowsbulls.Game')),
                ('guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowsbulls.Guess')),
            ],
        ),
    ]
