# Generated by Django 3.0.7 on 2020-07-03 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0002_auto_20200703_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='choices',
            field=models.CharField(editable=False, max_length=20000, validators=[django.core.validators.int_list_validator]),
        ),
    ]
