# Generated by Django 3.0.7 on 2020-07-07 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0003_auto_20200703_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='choices',
            field=models.CharField(max_length=20000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='game',
            name='guess',
            field=models.CharField(max_length=4),
        ),
    ]
