# Generated by Django 3.0.7 on 2020-07-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0004_auto_20200707_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
