# Generated by Django 3.0.7 on 2020-07-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0005_auto_20200707_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='game',
            name='input_error',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
