# Generated by Django 3.0.7 on 2020-07-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0006_auto_20200709_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='count',
        ),
    ]
