# Generated by Django 3.0.7 on 2020-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsbulls', '0007_remove_game_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cows', models.CharField(max_length=1)),
                ('bulls', models.CharField(max_length=1)),
                ('guess', models.CharField(max_length=4)),
            ],
        ),
    ]
